### ISSUE TITLE
How to use URL for image processing?

### ISSUE THREAD

**Issue by shallykumar19** [aimanfatima/Minor-Project#2]
https://debuggercafe.com/create-your-own-deep-learning-image-dataset/
I think this will be helpful for using url directly in our model.

**Comment by Naomi98** [comment]
Try to find a method to download the images sequentially (for instance, the names being started from 1, 2, ...) using the URLs provided in the data set [here](https://github.com/aimanfatima/Minor-Project/issues/1#issuecomment-552219995)

**Comment by Naomi98** [comment]
Use [Tab Save](https://chrome.google.com/webstore/detail/tab-save/lkngoeaeclaebmpkgapchgjdbaekacki) Chrome Extension for downloading the images all at once.

Steps to download the images:

1. Add the Chrome Extension and start it
2. Go to the edit (pencil at the bottom-left corner) option on the pop-up window
3. Paste the list of URLs you want to download in the space provided and click on Download button.

**Important Note**- Keep in mind to change the Chrome Download Settings by disabling the button "Ask where to save each file before downloading". Also, selecting a new folder as the by default option to save all the images. Otherwise, you'll have to click on Save button for each file.
